flowchart LR

%% Broadcast orders:
USER(("User"))

subgraph BROADCAST_SHARD["Broadcast order</br>(location sharded)"]
  BS_ORDER_SERVICE["Order Service"]
  BS_ORDER_DB[("Orders DB")]
  BS_QUEUE_ORDER_CREATED[/order.created/]
  BS_MATCHING_ENGINE["Matchmaking Engine"]
  BS_PROVIDERS_DB[("Providers DB")]
  BS_AWS_SNS["AWS SNS"]

  BS_ORDER_SERVICE -->|"Persists order"| BS_ORDER_DB
  BS_ORDER_SERVICE --> BS_QUEUE_ORDER_CREATED
  BS_QUEUE_ORDER_CREATED --> BS_MATCHING_ENGINE
end

BS_PROVIDER_1((Provider 1))
BS_PROVIDER_2((Provider 2))

USER -->|"Places order"| BS_ORDER_SERVICE
BS_MATCHING_ENGINE -->|"Queries"| BS_PROVIDERS_DB
BS_MATCHING_ENGINE --> BS_AWS_SNS
BS_AWS_SNS --> BS_PROVIDER_1 & BS_PROVIDER_2

%% Competitive claim:
PROVIDER(("Provider"))
subgraph COMPETITIVE_CLAIM["Competitive claim"]
  direction LR
  CC_FULFILLMENT_SERVICE["Fulfillment Service"]
  CC_QUEUE_ORDER_ATTEMPTED[/order.attempted/]
  CC_QUEUE_ORDER_RESOLVED[/order.resolved/]
  CC_ORDER_SERVICE["Order Service"]
  CC_ORDER_DB[("Orders DB")]
  CC_QUEUE_CLAIM_NOTIFICATION[/claim.notification/]
  CC_QUEUE_ORDER_FULFILLED[/order.fulfilled/]
  CC_NOTIFICATION_SERVICE["Notification Service"]

  CC_FULFILLMENT_SERVICE --- CC_QUEUE_ORDER_ATTEMPTED
  CC_FULFILLMENT_SERVICE --- CC_QUEUE_ORDER_RESOLVED
  CC_QUEUE_ORDER_ATTEMPTED & CC_QUEUE_ORDER_RESOLVED --- CC_ORDER_SERVICE
  CC_ORDER_SERVICE -->|"Updates order"| CC_ORDER_DB
  CC_ORDER_SERVICE --> CC_QUEUE_ORDER_FULFILLED
  CC_FULFILLMENT_SERVICE ----> CC_QUEUE_CLAIM_NOTIFICATION
  CC_QUEUE_ORDER_FULFILLED --> CC_NOTIFICATION_SERVICE
  CC_QUEUE_CLAIM_NOTIFICATION --> CC_NOTIFICATION_SERVICE
end

CC_PROVIDER(("Provider"))
CC_USER(("User"))

PROVIDER -->|"Attempts to claim order"| CC_FULFILLMENT_SERVICE
CC_NOTIFICATION_SERVICE --> CC_PROVIDER & CC_USER